### ISSUE TITLE
Interactive video: External video is without sound

### ISSUE THREAD

**Issue by pheraph** [Lumieducation/Lumi#1049]
I tried to insert an external MP4 video (from Panopto) into a H5P interactive video. This works in online authoring tools, but in Lumi the video plays no sound. It seems to be a specific problem in Lumi. For testing purposes I have attached an H5P file (renamed to .zip as this is an allowed file extension...) where I can reproduce the problem.

[interactive-content-110.zip](https://github.com/Lumieducation/Lumi/files/5652819/interactive-content-110.zip)

**Comment by sr258** [comment]
Thanks for the bug report. The problem doesn't seem to happen with all external MP4s. I've checked with the videos at http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5 and things work fine... I'll look into it why this doesn't work in your case. My first guess would be that this could be caused by codec issues. Lumi is based on Electron which is based on the Chromium web browser. It's possible that Electron doesn't include certain audio codecs. The video in your example works on a regular Chromium installation, however, so this might not be the real cause.

**Comment by sr258** [comment]
Nope, not a codec issue. The same file works fine when downloaded.

**Comment by JPSchellenberg** [comment]
@pheraph which OS are you using? I guess macOS, so it might be a macOS related issue. I will look into this. Do other audio files work?

**Comment by pheraph** [comment]
Yes, I am using macOS. Other audio and video are working totally fine. You can use the attached h5p file and try to reproduce under other operating systems.

**Comment by sr258** [comment]
The problem also exists on Linux

**Comment by pheraph** [comment]
I thought about it and If I had to guess, I would suspect that it is because the given embedded video has an audio track in the proprietary AAC format. I use myself a chromium build on macOS that has AAC enabled (compare your Chromium: http://html5test.com). Could it be that proprietary codecs are disabled in Electron (and thus in Lumi)? And maybe these are activatable?

<img width="827" alt="chromium" src="https://user-images.githubusercontent.com/58503/101642746-a3284300-3a33-11eb-9580-fb13cb8a1126.png">

**Comment by sr258** [comment]
I've also considered this as the source of the problem, but weirdly it works if you download the file to the local disk and then upload it in Lumi. The download file also has the aac codec, so it doesn't look like a codec issue after all.

I think we have to create a minimal Electron test app to check if the behavior is caused by Lumi code or by Electron. h5p-nodejs-library in the browser doesn't have this issue.

I can now also confirm that the problem exists in Windows 10 as well.

**Comment by sr258** [comment]
I've created a minimal Electron app that includes a video element with @pheraph's video source and the sound is played in this setup. So it must be something about H5P in Electron or Lumi in general, but not a general problem with Electron.

**Comment by sr258** [comment]
This problem will be resolved in the refactored frontend.
