### ISSUE TITLE
Error when trying to upload my library (work on Moodle)

### ISSUE THREAD

**Issue by DegrangeM** [Lumieducation/Lumi#1464]
**Describe the bug**
When I try to upload my library with the new functionnality of lumi I get an error.

**Environment (please complete the following information):**
 - OS: Windows 10
 - 7.1

**To Reproduce**
1. Download my library :
[libraries.txt](https://github.com/Lumieducation/Lumi/files/6331639/libraries.txt)
2. Rename to libraries.h5p
3. On lumi, go in option, library and upload the downloaded file
4. Lumi will display and error

**Additional context**
My Code Highlighter will still be partially installed : it will be listed but will not load correctly.
Uploading my library on moodle work without error and my library can be used without issue.

Bonus question : When trying to upload the files with api, lumi return an error 500 : is there a way to get more information about the error ?

**Comment by sr258** [comment]
You can use the demo server of h5p-nodejs-library. It's easy to use and gives you more verbose output if you start it with `DEBUG=h5p* LOG_LEVEL=debug npm start`.

There is something wrong with the files in the library: when copying the library you get "There was a consistency error when installing library CodeMirror-1.0. Reverting installation.".

The error thrown is: "EISDIR: illegal operation on a directory, open '/Users/sebastianrettig/Documents/h5p_dev/h5p-nodejs-library/packages/h5p-examples/h5p/libraries/CodeMirror-1.0/mode/asn.1'"

The reason is probably that "asn.1" looks like a file but is a directory. We have a glob like /**/*.* to copy files and it thinks asn.1 is a file. You might want to consider changing the directory name. I'll file an issue in h5p-nodejs-library, as this is something that should be fixed there.

**Comment by DegrangeM** [comment]
Thanks.

I close this issue as it's an h5p-nodejs-library issue.

**Comment by DegrangeM** [comment]
Is there a way to see why Lumi refuse to open an h5p file (not a library) ? The nodejs server is good to detect error for installing library but the demo doesn't allow to upload h5p file (not library).
