### ISSUE TITLE
npm ci on every branch change slows down development a lot

### ISSUE THREAD

**Issue by sr258** [Lumieducation/Lumi#268]
I understand the reasoning why Husky forces `npm ci` after every branch change, but I think this goes a bit too far currently:

Changing branches takes a long time now, as `npm ci` downloads a massive amount of data and creates thousands of files. Several of the dependencies can't be cached (Chrome download, H5P core data) and it takes several minutes to change a branch (and is sometimes not successful). My main development machine is really potent and things are still slow. I also have trouble pushing branches to GitHub (seems to take forever).

How about changing it to `npm install`?

**Comment by JPSchellenberg** [comment]
We can remove the `npm ci` from git-checkout. The idea was to have a clean install everytime you checkout a different branch, because in one branch there might be a dependency in v1.0.0 and in the other branch v1.0.1. `npm install` would not re-install the different versions of the dependency.
The push to GitHub is slow because it runs `npm run ci` - so all unit tests and so on.
