### ISSUE TITLE
Content width in player never changed

### ISSUE THREAD

**Issue by sr258** [Lumieducation/Lumi#342]
**Describe the bug**
If you open the player with content and later resize the window, the content width is not recalculated.

**What I'd expect**
The content is resized.

**Screenshot**
![lumi-player-width](https://user-images.githubusercontent.com/15268740/79047509-4dd33200-7c17-11ea-9eb9-c3706e4fa86b.gif)

**Comment by sr258** [comment]
Note: This only applies in certain content type. We might have to send the resized event in the iframe.

**Comment by otacke** [comment]
> Note: This only applies in certain content type. We might have to send the resized event in the iframe.

Just ran into that one. Yes. H5P content doesn't know that the environment outside the iframe resized and expects a _resize_ event that it can listen to - but that's actually pretty common among content types.

You can easily verify this by choosing the render context and then running
```
H5P.instances.forEach((instance) => {
  instance.trigger('resize');
});
```
The content will resize as required. You basically only would have to listen to the Window's _resize_ event and then trigger a resize on all content instances (or "the content instance" since Lumi only keeps one content at a time).

**Comment by sr258** [comment]
Thanks for the help here, @otacke . This made things much faster...
