### ISSUE TITLE
CSS preview

### ISSUE THREAD

**Issue by leonardocerliani** [Lumieducation/Lumi#656]
To improve the integration of H5P content on your own website, it is important to have a consistent style with the rest of the content on the page.

H5P offers the possibility to use a [custom CSS](https://h5p.org/documentation/for-developers/visual-changes). It would be great if Lumi would accept a css file that would allow previewing the created content as it will appear on the website. 

You can see an example in the screenshot below, where I adapted the font in the H5P content to be consistent with the table on the page.

![css_h5p](https://user-images.githubusercontent.com/1486312/88623824-185b3300-d0a6-11ea-89a2-d7cf9fc7713e.png)

**Comment by clbrsantana** [comment]
Any news on this feature? 

I'm starting to investigate ways to implement this feature since I need a way to further customize the appearance for branding purposes in a project. Any guidance is welcome 😄

If I got it right, the underlying h5p server [already has the methods](https://docs.lumi.education/advanced-usage/customization#adding-custom-scripts-and-styles-via-constructor-injection) for adding custom JS and CSS, but Lumi's interface doesn't offer any fields to upload files or write the custom code. Is this right?

I intend to add a text field on content edit screen where one can write CSS code, then Lumi would both inject this code on preview mode and exported files (H5P and HTML)

One should be able to open a H5P file with custom CSS and edit the code on the same field.

We could also have a field on settings page where someone can write custom code and that would be inserted in all new files (like a default custom CSS).

**Comment by sr258** [comment]
It's still on our roadmap, but we're swamped with work for a - soon to be released under GPL 3 as well - player offshot of Lumi and our day job work... So there was only time to fix critical bugs in Lumi. Hopfully, this will improve in the next few weeks...

The underlying server only partly supports what we need for it:

- You can add custom scripts to the player, but only when you initialize the H5PPlayer object. The lifetime of this object is throughout a session in Lumi, so this is not a good place for adding styles for content.
- You can also set custom scripts in the config, but again it's a global flag.

What need to be changed is that we have to pass the custom scripts to the H5PPlayer.render method on a per-content basis.

The same is true for HtmlExporter. You might be able to work with the `template` constructor object, which adds the "frame" around the exported HTML. But ideally, there's a parameter that adds custom HTML in the methods that create the exports.

**Comment by sr258** [comment]
It only took 1 1/2 years, but the latest beta now includes the ability to add custom css in exports.
